version: "3.7"

services:
  postgres:
    container_name: pg_management_system
    image: postgres:17.1
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "work_mem=8MB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"
      - "-c"
      - "log_min_duration_statement=300ms"
      - "-c"
      - "idle_in_transaction_session_timeout=15s"
      - "-c"
      - "lock_timeout=2s"
      - "-c"
      - "statement_timeout=30s"
    environment:
      POSTGRES_DB: "management_system"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/management_system'
      JAVA_OPTS: '-Xmx512m'
volumes:
  postgres_data: