server:
  port: 8080

spring:
  application:
    name: task-management-system
  datasource:
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/management_system
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
